# Generated by Django 2.0.8 on 2018-08-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_fn', models.CharField(max_length=100, verbose_name='First Name')),
                ('artist_ln', models.CharField(max_length=200, verbose_name='Last Name')),
                ('artist_created_ts', models.DateTimeField(auto_now=True)),
                ('artist_published_ts', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_prid_a', models.IntegerField(default=0)),
                ('artwork_prid_b', models.IntegerField(default=0)),
                ('artwork_title', models.CharField(max_length=200, verbose_name='Title')),
                ('artwork_year_a', models.DateField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Artist', verbose_name='Artist')),
            ],
        ),
    ]
