# Generated by Django 2.0.8 on 2018-08-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20180809_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork_prid_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_prid_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_yyyy_a',
            field=models.IntegerField(default=1900),
        ),
    ]
