# Generated by Django 2.0.8 on 2018-08-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20180809_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artwork_year_a',
        ),
    ]
