# Generated by Django 2.0.8 on 2018-08-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_auto_20180809_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artwork_yyyy_b',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_yyyy_a',
            field=models.IntegerField(default=1900, verbose_name='Date'),
        ),
    ]
