# Generated by Django 2.0.8 on 2018-08-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_artist_artist_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N/A', 'N/A')], max_length=3, null=True, verbose_name='Sex'),
        ),
    ]
