# Generated by Django 2.0.8 on 2018-08-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_auto_20180809_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artwork_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
