# Generated by Django 2.0.8 on 2018-08-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_artwork_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artwork_prid_a',
            new_name='prid_a',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='artwork_prid_b',
            new_name='prid_b',
        ),
        migrations.AddField(
            model_name='artist',
            name='wiki',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='size_x',
            field=models.CharField(max_length=15, null=True, verbose_name='Height'),
        ),
    ]
