# Generated by Django 2.0.8 on 2018-08-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_auto_20180810_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='size_y',
            field=models.CharField(max_length=15, null=True, verbose_name='Width'),
        ),
    ]
