# Generated by Django 2.0.8 on 2018-08-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_ledger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_fn',
            new_name='fn',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_ln',
            new_name='ln',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_sex',
            new_name='sex',
        ),
    ]
